export const getClients = 'getClients'
export const getApplicants = 'getApplicants'
export const addApplicantData = 'addApplicantData'
export const delApplicant = 'delApplicant'
export const client = 'client'
export const arrayIndexApplicant = 'arrayIndexApplicant'
export const jsonDATA = 'jsonDATA'
